version: "3"
services:
  studydb :
    container_name: postgres2
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sumin
      - POSTGRES_PASSWORD=suminpassword
      - POSTGRES_DB=studydb